.TH DETECTLOADER 8 "Apr 2000-2004" "initscripts" "Mandriva"
.SH NAME
detectloader \- Detect what type of loader you have on your disk.
.SH LIMITATION
.PP
Supports only grub, lilo, and yaboot (the boot loaders we use for \fBMageia
Linux\fR). Patches welcome for other boot loaders.
.SH COPYRIGHT
Copyright \(co 1999-2004 Mandriva.
Copyright \(co 2010-2011 Mageia.
.PP
This is free software; see the source for copying conditions.  There
is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
